name: Commit Update Check
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line commit check script
        run: echo This is a one line script test for the commit check
      - name: Run a multi-line script
        run: |
          echo This is a multiline output for a successful commit check,
          echo You have successfully made a commit in GitHub
