name: CI
on:
  push:
    branches: [ "main" ]
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Testing, 1, 2, 3
     - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo You have successfully made a commit in GitHub
